import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
import { withIronSessionSsr } from "iron-session/next";
import { sessionOptions } from '../libs/session';

export default function Home({ user }) {

  return (
    <div className={styles.container}>
      <Head>
        <title>SingUp | Sos Mi Tipo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/fav.png" />
      </Head>

      <main className={styles.main}>
        <h3>Index</h3>
        <Link href="/login"><a>Ingresar</a></Link>
        <Link href="/singup"><a>Registrarse</a></Link>
      </main>
    </div>
  )
}

export const getServerSideProps = withIronSessionSsr(async function getServerSideProps({ req }){
  const user = req.session.user
  if(!user){
    return {
      redirect: {
        destination: '/login',
        permanent: false
      }
    }
  }

  return {
    props:{
      user
    }
  }
}, sessionOptions)