import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h3 className={styles.title}>
          ¡Crea tu cuenta!
        </h3>
        <form className={styles.form}>
          <input placeholder='Email' className={styles.input}></input>
          <input placeholder='Password' className={styles.input}></input>
          <input placeholder='Country' className={styles.input}></input>
          <input placeholder='City' className={styles.input}></input>
          <input type="submit" className={styles.input} value="Login"></input>
        </form>
      </main>
    </div>
  )
}
