import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
import Main from '../atoms/Main/Main';
import { withSessionSsr } from '../libs/withSession'

export default function Home({ user }) {

    const defaultPanelButtons = (<>
        <Link href="/login"><a>Ingresar</a></Link>
        <Link href="/singup"><a>Registrarse</a></Link>
    </>)

    const userPanelButton = (<>
        <Link href="/home"><a>Home</a></Link>
    </>)

    return (
        <div className={styles.container}>
            <Head>
                <title>Sos Mi Tipo</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/fav.png" />
            </Head>

            <Main>
                <h3>Index</h3>
                { user ? userPanelButton : defaultPanelButtons }
            </Main>
        </div>
    )
}

export const getServerSideProps = withSessionSsr(async function getServerSideProps({ req }) {
    const user = req.session.user

    return {
        props: {
            user: user ? user : null
        }
    }
})